name: eerl_app
description: "EERL App — A production-ready Flutter application."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Icons
  cupertino_icons: ^1.0.8

  # Localization
  intl: any

  # State Management
  provider: ^6.1.2

  # Local Storage
  shared_preferences: ^2.3.4

  # Navigation
  go_router: ^14.8.1
  flutter_svg: ^2.3.0
  lottie: ^3.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
    - assets/lottie/

  fonts:
    - family: Manrope
      fonts:
        - asset: assets/font/Manrope-Regular.ttf
        - asset: assets/font/Manrope-ExtraLight.ttf
          weight: 200
        - asset: assets/font/Manrope-Light.ttf
          weight: 300
        - asset: assets/font/Manrope-Medium.ttf
          weight: 500
        - asset: assets/font/Manrope-SemiBold.ttf
          weight: 600
        - asset: assets/font/Manrope-Bold.ttf
          weight: 700
        - asset: assets/font/Manrope-ExtraBold.ttf
          weight: 800
